# Development only!

version: '3'

volumes:
  pg_data:

networks:
  nasa:

services:
  db:
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    networks:
      - nasa
